{{- if .Values.Secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.Secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
