apiVersion: v1
kind: Secret
metadata:
  name: backendsecret
  namespace: production
stringData:
  DATABASE_URL: postgresql://postgres:password@postgres-sts-0.dbsvc.production.svc.cluster.local:5432/postgres
type: Opaque
