apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "6Gi"
    limits.cpu: "8"
    limits.memory: "12Gi"
    configmaps: "3"
    persistentvolumeclaims: "2"
    pods: "10"
    secrets: "3"
    requests.storage: "50Gi"
