name: Frontend CI/CD

on:
  push:
    branches:
    - main
    paths:
    - frontend/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Build Dockerimage
        run: docker build -f frontend/Dockerfile -t frontendimage frontend

      - name: push to registry (ECR)
        uses: jwalton/gh-ecr-push@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: frontendimage:latest
          image: frontend:latest

   deploy:
     runs-on: ubuntu-latest
     steps:
      # --- #
      - name: Build and push CONTAINER_NAME
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          eks_role_arn: ${{ secrets.EKS_ROLE_ARN }}
          kubernetes_version: v1.35
          args: rollout restart deployment frontend-deployment -n production
      # --- #

  #deploy:
    #runs-on: self-hosted
    #needs: build_and_push

    #steps:
      #- name: Deployment rollout
        #run: kubectl rollout restart deployment frontend-deployment -n production
    
