name: Frontend CI/CD

on:
  push:
    branches:
    - main
    paths:
    - frontend/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Build Dockerimage
        run: docker build -f frontend/Dockerfile -t frontendimage frontend

      - name: push to registry (ECR)
        uses: jwalton/gh-ecr-push@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: frontendimage:latest
          image: frontend:latest
     
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
       # - name: Generate kubeconfig
       #   run: |
       #     {
       #      echo 'EKS_CREDS<<EOF'
       #      aws eks update-kubeconfig --region us-east-2 --name my-cluster --dry-run | base64
       #      echo EOF
       #     } >> $GITHUB_ENV
       - uses: tale/kubectl-action@v1
         with:
           base64-kube-config: ${{ secrets.KUBE_CONFIG }}
       - run: kubectl rollout restart deployment frontend-deployment -n production
  #deploy:
    #runs-on: self-hosted
    #needs: build_and_push

    #steps:
      #- name: Deployment rollout
        #run: kubectl rollout restart deployment frontend-deployment -n production
    
