name: Frontend CI/CD

on:
  push:
    branches:
    - main
    paths:
    - frontend/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Build Dockerimage
        run: docker build -f frontend/Dockerfile -t frontendimage frontend

      - name: push to registry (ECR)
        uses: jwalton/gh-ecr-push@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: frontendimage:latest
          image: 358454002832.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
